AllCops:
  Include:
    - '**/*.rb'
  TargetRubyVersion: 2.5


Layout/CaseIndentation:
  EnforcedStyle: end
  IndentOneStep: true
  SupportedStyles:
    - case
    - end

Layout/LineLength:
  Exclude:
    - spec/**/*_spec.rb

Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space
  SpaceBeforeBlockParameters: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space


Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Metrics/MethodLength:
  Enabled: false


Naming/FileName:
  Exclude:
    - Rakefile
    - Gemfile


Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/TrivialAccessors:
  AllowPredicates: true
