sudo: false
dist: bionic
language: ruby
rvm:
  - 2.7.0
  - 2.6.5
  - 2.5.7
gemfile:
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
  - gemfiles/rack_2.0.gemfile
  - gemfiles/rack_2.1.gemfile
  - gemfiles/rack_2.2.gemfile
