on: [push, pull_request]
jobs:
  rubocop:
    name: rubocop
    runs-on: ubuntu-20.04

    env:
      BUNDLE_WITHOUT: development
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3

    steps:
      - uses: actions/checkout@master
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - run: bundle exec rubocop --parallel --color
