name: Test
on: [push]
jobs:
  test:
    name: Ruby ${{ matrix.ruby }} / ${{ matrix.gemfile }}
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        ruby:
          - '2.7'
          - '2.6'
          - '2.5'
        gemfile:
          - rails_5.0.gemfile
          - rails_5.1.gemfile
          - rails_5.2.gemfile
          - rails_6.0.gemfile
          - rack_2.0.gemfile
          - rack_2.1.gemfile
          - rack_2.2.gemfile
      fail-fast: false

    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}
      BUNDLE_WITHOUT: development
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3

    steps:
      - uses: actions/checkout@master

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - run: bundle exec rspec --color --format documentation
